version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=somepass111
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  blog:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - ./static/:/static

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
      - blog
    ports:
      - "80:80"
    volumes:
    - ./static/:/static

